#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

# npm test

# run Typescript types check on all repo
echo "Running Typescript check.."
npm run tsc:check
LINTER_EXIT_CODE=$?
echo "Typescript check - Done"

# run Prettier on staged files
echo ""
echo "Running Prettier..✨✨✨"
npm run prettier:write $STAGED_FILES
echo "Prettier formatting - Done"

# add files auto-fixed by the linter and prettier
git add -f $STAGED_FILES

# run linter on staged files
echo ""
echo "Running Linter..⚒️⚒️⚒️"
npm run lint
LINTER_EXIT_CODE=$?
echo "Linting - Done"
echo ""

# check linter exit code
if [ $LINTER_EXIT_CODE -ne 0 ]; then
    echo "No, no, no! fix those lint errors first..😠"
    exit 1
else
    echo "lint all good..👍"
fi

# # run tests related to staged files
# echo "Running Tests"
# ./node_modules/.bin/jest --bail --findRelatedTests $STAGED_FILES --passWithNoTests
# JEST_EXIT_CODE=$?

# # check jest exit code
# if [ $JEST_EXIT_CODE -ne 0 ]; then
#     echo "Please you can do better than this..🙏🙏🙏"
#     exit 1
# else
#     echo "test all good..👍"
# fi

# return 0-exit code
echo "🎉 you are a rockstar..🔥🔥🔥"
exit 0
